name: NodeJS with yarn

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        yarn build
        zip -r production-build.zip lib/js/
        ls
        pwd
  upload-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
     - uses: actions/upload-artifact@v3
       with:
         name: production-build
         path: ./production-build.zip
  download-build:
    runs-on: ubuntu-latest
    needs: upload-build
    steps:
     - uses: actions/download-artifact@v3
       with:
         name: production-build
     - name: create release
       id: create_release
       uses: actions/upload-release-asset@v1.0.1
       env:
         GITHUB_TOKEN: ${{ secrets.TK }}
       with:
         tag_name: ${{ github.run_number }}
         release_name: "literally_canvas"
      
     - name: upload_release
       id: upload_release
       uses: actions/upload-release-asset@v1.0.1
       env:
         GITHUB_TOKEN: ${{ secrets.TK }}
         assetName: production-build
       with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: ${{ env.assetName }}.zip
         asset_name: ${{ env.assetName }}.zip
         asset_content_type: application/zip
